### PR TITLE
Fix `summary` month issues and inaccurate messages

### LINKED ISSUE #217: [PE-D][Tester A] Summary with no transactions
Steps to reproduce: Run summary on a person and a range with no transactions

Expected: Should display that there are no transactions

REsult: Show transaction total is $0

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: fusin02/ped#9

### LINKED ISSUE #224: [PE-D][Tester C] Find feature bug - inaccurate message generated
The terminology used in the generated message for finding clients should be “client(s)” instead of “person(s)”, the use of "person(s)" does not align with the terminology “clients” specified in the UG, DG and JAR file.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: jolynleow2301/ped#10

### LINKED ISSUE #227: [PE-D][Tester E] Summary year is not showing the correct year in the command window
When i input summary s/0000-09 e/0000-10 the command log changes the year to 0001 instead

Exact command:summary s/0000-09 e/0000-10

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: rubinnn/ped#10

### PR DESCRIPTION
**Pull request by reginateh**
Fixes #227 
Any 4-digit integer is valid year including negative numbers (represent BC). 
`summary s/-0001-01 e/0000-01`
image

Fixes #224 
Changed every "person" to "client" in `Message.java` 
Changed every "person" to "client" in `FindCommand.java`

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/SummaryCommand.java [hunk 1]
```diff
@@ -26,6 +26,8 @@ public class SummaryCommand extends Command {
             + "Example: " + COMMAND_WORD + " " + PREFIX_START_MONTH + "2024-09 " + PREFIX_END_MONTH + "2024-12";
 
     public static final String MESSAGE_SUCCESS = "The total amount of transactions from %s to %s is: %s";
+    public static final String MESSAGE_NO_TRANSACTIONS_FOUND = "No transactions found from %s to %s";
+
```
Comment (kngys) [inline src/main/java/seedu/address/logic/commands/SummaryCommand.java:30]: I think we're not allowed to change or add any messages shown to the user because of the feature freeze, except the particular cases shown here.
image

**Review by kngys — COMMENTED** [review]
I think need to resolve some merge conflicts after I merged in my previous pull request

File: src/main/java/seedu/address/logic/commands/SummaryCommand.java (hunk 1 above)
Comment (reginateh) [reply src/main/java/seedu/address/logic/commands/SummaryCommand.java:30]: Hmmm ok so should I just close the issue? Or maybe it qualifies as fails silently? 😅

Comment (beginner-web-developer) [reply src/main/java/seedu/address/logic/commands/SummaryCommand.java:30]: I think its not allowed idk. I think what they meant by "fail silently" is like an error occured but no message to the user on what happened

Comment (reginateh) [reply src/main/java/seedu/address/logic/commands/SummaryCommand.java]: Ok removed the changes in [e0b67e4](https://github.com/AY2425S1-CS2103T-F13-4/tp/pull/257/commits/e0b67e4900a185b7b3169018799f0bf31f73ed20)

**Comment by beginner-web-developer** [comment]
LGTM
